### ISSUE TITLE
tutorial/readme

### ISSUE THREAD

**Issue by fcakyon** [FrancescoSaverioZuppichini/Modern-Python-Doc-Example#1]
I am very interested in what you are doing here. Do you have any intentions for sharing a tutorial on how to setup this project? :)

**Comment by FrancescoSaverioZuppichini** [comment]
Hi! Yes, I am working on it :)

**Comment by FrancescoSaverioZuppichini** [comment]
You can have a look at the README :)

**Comment by fcakyon** [comment]
Awesome :100:
