### ISSUE TITLE
pencil icon throws 404

### ISSUE THREAD

**Issue by fcakyon** [FrancescoSaverioZuppichini/Modern-Python-Doc-Example#2]
This repo is pure gem :100: 

I have one question. When I click the pencil icon in any page (for instance top right in this page: https://francescosaveriozuppichini.github.io/Modern-Python-Doc-Example/), it shows 404 page error. Is it expected?

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot :)

Oh no, nice catch! I'll investigate

**Comment by FrancescoSaverioZuppichini** [comment]
The button points by default to the `master` branch, while nowadays we use `main` instead

**Comment by FrancescoSaverioZuppichini** [comment]
Fixed, I had to add the `edit_uri: edit/main/docs` param to the `yml` file :)
